### ISSUE TITLE
In Webserver always show PS in preformatted text

### ISSUE THREAD

**Issue by andimik** [clorenz/TEFBandscan#22]
If a station contains a leading space in the PS, this is logged, for example

```
"101100","5293"," FRECCIA","0","1","32","9","0","2024-06-05T18:29:54.843220135"
"102900","A213","  FM4   ","0","0","47","4","0","2024-06-05T18:30:04.281409742"
```

but not shown on the webserver.

![grafik](https://github.com/clorenz/TEFBandscan/assets/24510556/24523fd9-c187-4f97-a490-62e131d0c272)

**Comment by clorenz** [comment]
fixed
